name: 🚀 Feature request
description: Suggest a feature for the library
title: "[FEATURE] <title>"
labels: [enhancement, needs triage]

body:
- type: textarea
  attributes:
    label: Description
    description: A clear and concise description of the problem or missing capability.
  validations:
    required: true

- type: textarea
  attributes:
    label: Proposed solution
    description: If you have a solution in mind, please describe it.
  validations:
    required: true

- type: textarea
  attributes:
    label: Alternatives considered
    description: Have you considered any alternative solutions or workarounds?
  validations:
    required: false
