name: Release library

on:
  release:
    types: [created]

jobs:
  ci_release:
    uses: badisi/actions/.github/workflows/action.yml@v2
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    with:
      build: true
      release: true
