name: Release library

on:
  release:
    types: [created]

jobs:
  ci_release:
    uses: dsi-hug/action/.github/workflows/action.yml@v1
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    with:
      release: true
